title: Videojs Annotation Comments
description: A plugin for video.js to add support for timeline moment/range comments and annotations
show_downloads: true
google_analytics: 
theme: jekyll-theme-cayman